### PR TITLE
Import Northern Ireland charities

### PR DESCRIPTION
**Pull request by BobHarper1**
NI Charity Commission register of charities .CSV available from http://www.charitycommissionni.org.uk/charity-search/

CCNI numbers in the dataset are pure numbers (e.g. 100012), but the NI Charities can be identified with the 'NIC' prefix which I have used here (though not to the `_id` field)

I haven't done anything to find dual registries w.r.t. the NI charities (not quite sure what it involves or if it affects NI register). Also, the population of the NI register is still in progress so would probably put that work on hold in any case.

I've also added links to the charity pages on the respective Commission websites to the `charity.html` view

### CODE REVIEW

**Comment by drkane** [comment]
Hi @BobHarper1 - really sorry I've only just noticed this, not sure why I didn't get a notification.

This looks amazing. I think the last time I tried the Export CSV link from the CCNI website it only had 500 rows, but great that it's now giving all of them. 

It all looks great - I'm just going to check the changes locally but they look fine to merge to me.

**Comment by drkane** [comment]
On the dual registration, my sense is that there's not so much overlap between the three jurastictions as there is with CCEW <> OSCR, but you'll know better than I do on that.

**Comment by drkane** [comment]
In terms of the ID numbers - personally I would go for "NIC101234" for the `_id` field, and then "101234" for `ccni_number`. 

The justification for this would be that I'd be worried about potential collisions between the CCEW & CCNI numbers - although there's none at the moment they do both have six-digit id numbers so there's a theoretical possibility. And it makes sense if the CCNI don't use a prefix for that official number to be stored in `ccni_number`.

(I am slightly aware that leaving the CCEW charity numbers without a prefix seems a bit anglo-centric - I guess the justification is that it's based on the conventions generally used by charities themselves)

**Comment by BobHarper1** [comment]
Hi @drkane, no problem. We're looking at making improvements to NICVA's database of vol/comm organisations through reconciling with the NI Register, as well as CCEW and OSCR, so being able to use your repo here has been a great benefit.

Some more information because I've done some work since my original message:

- I also [beefed up](https://github.com/TechforgoodCAST/find-that-charity/pull/1/commits/34b73c517c90ca9788ed72e8f7d1d2bb51561869) the reconcile specification so that it would work against the OpenRefine API.

- I have a scraper program to get more information from the CCNI website that available from the downloadable csv, most importantly 'other names'. I'll maintain these in the Gist - fetch_data will download it from there and import_data will add it to the model.

**Comment by BobHarper1** [comment]
Take your point on the `_id` field, yes there are some CCEW number formats that are very close to the basic CCNI format (all '10****') so wise to avoid.

I don't think there is much of an issue about dual registrations between NI > OSCR/CCEW. Any potentials I can think of are fully separate entities, for example [Oxfam Ireland](http://www.charitycommissionni.org.uk/charity-details/?regid=100848&subid=0) which is registered as an [NI company](https://beta.companieshouse.gov.uk/company/NI033800). We could look and see if there are any duplicate company numbers for CCNI charities but do doubt there will be any.

**Comment by drkane** [comment]
@BobHarper1 great stuff - particularly doing the proper recon api which has ticked an item off my todo list! I've merged this PR and made a few more changes this afternoon.

Good to collaborate like this!

**Pull request merged**
